---
# tasks file for ansible-role-node_exporter

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Start node_exporter
  service:
    name: "{{ node_exporter_service }}"
    enabled: true
    state: started
